apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned
  # annotations:
  #   argocd.argoproj.io/sync-wave: "5"
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  selfSigned: {}
